### ISSUE TITLE
 Unknown key in field texts.resendVerificationEmailLink_pre

### ISSUE THREAD

**Issue by dstollie** [meteor-useraccounts/core#380]
Im  getting the following error whenever i want to set the following texts:

```
AccountsTemplates.configure({
    texts: {
        resendVerificationEmailLink_pre: "E-mailbevestiging niet ontvangen?",
        resendVerificationEmailLink_link: "Opnieuw versturen"
    }
});
```

```
W20150507-10:50:55.192(2)? (STDERR)           
W20150507-10:50:55.193(2)? (STDERR) /Users/dennisthemanice/.meteor/packages/meteor-tool/.1.1.3.v2mbkx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150507-10:50:55.193(2)? (STDERR)                                             throw(ex);
W20150507-10:50:55.193(2)? (STDERR)                                                   ^
W20150507-10:50:55.221(2)? (STDERR) Error: Match error: Unknown key in field texts.resendVerificationEmailLink_pre
W20150507-10:50:55.221(2)? (STDERR)     at packages/check/match.js:299:1
W20150507-10:50:55.221(2)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150507-10:50:55.222(2)? (STDERR)     at checkSubtree (packages/check/match.js:290:1)
W20150507-10:50:55.222(2)? (STDERR)     at packages/check/match.js:296:1
W20150507-10:50:55.222(2)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150507-10:50:55.222(2)? (STDERR)     at checkSubtree (packages/check/match.js:290:1)
W20150507-10:50:55.222(2)? (STDERR)     at check (packages/check/match.js:32:1)
W20150507-10:50:55.222(2)? (STDERR)     at [object Object].AT.configure (packages/useraccounts:core/lib/core.js:481:1)
W20150507-10:50:55.222(2)? (STDERR)     at app/lib/config/account-templates.js:17:19
W20150507-10:50:55.222(2)? (STDERR)     at app/lib/config/account-templates.js:60:3
```

**Comment by splendido** [comment]
ops!
The [texts pattern](https://github.com/meteor-useraccounts/core/blob/3862dd2ffee16902c9c94cc015cc0bbea3546c34/lib/core.js#L53-83) is missing all `resendVerificationEmailLink_*` keys... :(

**Comment by splendido** [comment]
Tnx for reporting!
