### ISSUE TITLE
Exception while invoking method 'ATCreateUserServer' Error: Match error: Expected object, got string

### ISSUE THREAD

**Issue by zacharynevin** [meteor-useraccounts/core#393]
I am trying to use useraccounts:core to create a username/password registration system. The frontend code I have is the following:

````
Meteor.call('ATCreateUserServer', {
    profile: {
        name: form.fname.value + ' ' + form.lname.value,
    },
    email: form.email.value,
    password: form.password.value
}, function(err) {
// do stuff
});
````

When I do this, I get the error in the title. The full stacktrace is the following:
````
Exception while invoking method 'ATCreateUserServer' Error: Match error: Expected object, got string
    at checkSubtree (packages/check/match.js:275:1)
    at check (packages/check/match.js:32:1)
    at packages/useraccounts:core/lib/methods.js:63:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts:core/lib/methods.js:56:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
Sanitized and reported to the client as: Match failed [400]
````

In the code, it looks like this line, where we see `check(value, Object)`:
````
if (fieldId === "password"){
  // Can"t Pick-up password here
  // NOTE: at this stage the password is already encripted,
  //       so there is no way to validate it!!!
  check(value, Object);
  return;
}
````
Thank you for your help!

**Comment by splendido** [comment]
you found the right line! :-)
The password should be encrypted: see [these lines](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L186-192)
