### ISSUE TITLE
Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by ShawnOceanHu** [meteor-useraccounts/core#419]
Hi guys,
I was getting this very strange error "Cannot read property '_id' of undefined", here's the stack trace:

```
I20150607-07:23:04.407(8)? Exception while invoking method 'ATCreateUserServer' TypeError: Cannot read property '_id' of undefined
I20150607-07:23:04.407(8)?     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:244:1)
I20150607-07:23:04.407(8)?     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
I20150607-07:23:04.407(8)?     at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1017:1)
I20150607-07:23:04.407(8)?     at createUser (packages/accounts-password/password_server.js:718:1)
I20150607-07:23:04.407(8)?     at Object.Accounts.createUser (packages/accounts-password/password_server.js:776:1)
I20150607-07:23:04.408(8)?     at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts:core/lib/methods.js:105:1)
I20150607-07:23:04.408(8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150607-07:23:04.408(8)?     at packages/ddp/livedata_server.js:648:1
I20150607-07:23:04.408(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150607-07:23:04.408(8)?     at packages/ddp/livedata_server.js:647:1
```

It seems when aldeed's collection2 package tries to validate the new created user document, it somehow is undefined. 

Here's my AT configs:

```
AccountsTemplates.configure({
    hideSignInLink: true,
    hideSignUpLink: true,
    showLabels: false,
    showForgotPasswordLink: true,
    negativeValidation: true,
    defaultState: 'signIn',
    overrideLoginErrors: false,
    sendVerificationEmail: true,
    negativeValidation: true,
    negativeValidation: true,
    negativeFeedback: true,
    positiveFeedback: true,
    showValidating: true,
    onSubmitHook: function(error, state) {
      if (!error) {
        switch (state) {
          case "signIn":
            switch (error.error) {
              case 403:
                console.log("sorry, can't find this user, have you registered ?");
                break;
            }
            break;
          case "signUp":
            break;
        }
      }
    },
});
```

**Comment by ShawnOceanHu** [comment]
Hi guys, just found the problem, forgot to return the "user" in Accounts.onCreateUser.
There's too much noise in my mind : )
