### ISSUE TITLE
Email Issue

### ISSUE THREAD

**Issue by a-db** [meteor-useraccounts/core#427]
It doesn't seem to matter what I try but I just can't seem to get email working. This means no password reset functionality. I am using mup with a correct MAIL_URL set. It appears to authenticate just fine but I can never get past this error: 
```
RecipientError: Can't send mail - all recipients were rejected
    at Object.Future.wait (/opt/23design/app/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/email/email.js:76:1)
    at Object.Email.send (packages/email/email.js:153:1)
    at Object.Email.send (packages/meteorhacks:kadira/lib/hijack/email.js:10:1)
    at Object.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:421:1)
    at [object Object].Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:365:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:161:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
    at SMTPClient._actionRCPT (/opt/23design/app/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:909:27)
    at SMTPClient._onData (/opt/23design/app/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:329:29)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickCallback (node.js:442:13)
```

**Comment by a-db** [comment]
If anyone else runs into this problem. Which actually is just part of the meteor bundle and not this package. Make sure you set your from address in meteor startup like below. This is cause by SMTP security. Would be nice if documented more explicitly on the meteor docs.

Accounts.emailTemplates.from = "Myself <me@myself.com>";
