### ISSUE TITLE
Change password form shows error "Match failed"

### ISSUE THREAD

**Issue by devagrawal09** [meteor-useraccounts/core#762]
I used `{{> atForm state="changePwd"}}` in my app to change password. when i enter the new password and submit, it doesn't save, instead shows an error saying "Match failed".  I get this error on the server console - 

```
I20180523-23:40:38.158(5.5)? Exception while invoking method 'changePassword' Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
I20180523-23:40:38.167(5.5)?     at check (packages/check/match.js:36:17)
I20180523-23:40:38.169(5.5)?     at MethodInvocation.changePassword (packages/accounts-password/password_server.js:465:3)
I20180523-23:40:38.171(5.5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180523-23:40:38.172(5.5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180523-23:40:38.172(5.5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1186:12)
I20180523-23:40:38.176(5.5)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180523-23:40:38.176(5.5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1186:12)
I20180523-23:40:38.177(5.5)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180523-23:40:38.177(5.5)?     at new Promise (<anonymous>)
I20180523-23:40:38.178(5.5)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180523-23:40:38.178(5.5)?     at packages/ddp-server/livedata_server.js:559:43
I20180523-23:40:38.179(5.5)? Sanitized and reported to the client as: Match failed [400]
```

for now I have created a custom form to change passwords, but I shouldn't if I have the useraccounts package. This issue needs to be fixed.
Im using google chrome on Windows 10.

**Comment by adrianflda** [comment]
i have the same issue, any answer???

**Comment by ddaydd** [comment]
Hello, same issue with 
`{{> atForm state='resetPwd'}}`
 any news?

Edit:

work like this

```
import '../import/ui/registration/reset-password.js';
AccountsTemplates.configureRoute('resetPwd', {
  name: 'appResetPwd',
  template: 'appResetPwd',
  path: '/reset-password',
});
```

but not like this

```
Router.route('/reset-password/:token', {
  name: 'appResetPwd',
  template: 'appResetPwd',
  onBeforeAction: function () {
    import '../import/ui/registration/reset-password.js';
    this.next();
  }
});

AccountsTemplates.configureRoute('resetPwd', {
  path: '/reset-password',
});
```
